### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no unix-java in java.library.path

### ISSUE THREAD

**Issue by ranigupta1295** [tongo/ble-java#8]
As mentioned we installed libdbus-java on pi
command 
 sudo apt-get install libdbus-java

BLUEZ version 5.47 installed

Compiled the source but when we execute we get below error

java.lang.UnsatisfiedLinkError: no unix-java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at cx.ath.matthew.unix.UnixSocket.<clinit>(UnixSocket.java:40)
	at org.freedesktop.dbus.Transport.connect(Transport.java:772)
	at org.freedesktop.dbus.Transport.<init>(Transport.java:737)
	at org.freedesktop.dbus.DBusConnection.<init>(DBusConnection.java:299)
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:282)
	at it.tangodev.ble.BleApplication.start(BleApplication.java:76)
	at example.ExampleMain.<init>(ExampleMain.java:69)
	at example.ExampleMain.main(ExampleMain.java:86)

Are we missing something here?

**Comment by tongo** [comment]
Hi, you also need the _unix.jar_ library.
You can find it in the _libs_ folder:
https://github.com/tongo/ble-java/tree/master/libs

You also need the other library in that folder, include it in your project.
Let me know if you resolve.

**Comment by ranigupta1295** [comment]
I added all the 3 libraries present in link https://github.com/tongo/ble-java/tree/master/libs
in the library and also executable jar project of raspberry pi, still getting the same error as mentioned before.

![image](https://user-images.githubusercontent.com/28503724/50154826-7df31500-02f0-11e9-9af5-d466cd4ca20f.png)

I tried adding linunix-java.so to the lib folder of executable jar project.
Also tried to explicitly set the library path.

![image](https://user-images.githubusercontent.com/28503724/50155088-2b662880-02f1-11e9-88fd-3ca07e830378.png)

Please suggest me if I am missing something.

**Comment by tongo** [comment]
Try to add "-Djava.library.path=/usr/lib/jni" parameter to your jar call:
sudo java -jar -Djava.library.path=/usr/lib/jni /home/pi/YOUR_JAR

This tell java where is unix-java library installed

**Comment by ranigupta1295** [comment]
Thanks.  It worked.
